name: "Manual terraform workflow"

on:
  workflow_dispatch:
  #push:
  #  branches:
  #    - main
  #pull_request:
  #  branches:
  #    - main
  #pull_request_target:
  #  branches:
  #    - master

jobs:
  terraform_fmt:
    name: "Terraform fmt"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: "Setup Terraform"
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.9.8
          cli_config_credentials_token: ${{ secrets.TF_API_KEY }}

      - name: "Terraform init"
        run: |
          terraform init -backend=false

      - name: "Terraform fmt"
        run: |
          terraform fmt -check -recursive

  terraform_validate:
    name: "Terraform validate"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: "Setup Terraform"
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.9.8
          cli_config_credentials_token: ${{ secrets.TF_API_KEY }}

      - name: "Terraform init"
        run: |
          terraform init -backend=false

      - name: "Terraform validate"
        run: |
          terraform validate

  terraform_plan:
    needs: [terraform_validate, terraform_fmt]
    name: "Terraform plan"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: "Setup Terraform"
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.9.8
          cli_config_credentials_token: ${{ secrets.TF_API_KEY }}

      - name: "Terraform init"
        run: |
          terraform init

      - name: "Terraform plan"
        run: |
          terraform plan -var="api=${{ secrets.API_DO }}" -input=false -out=tfplan

      - name: "Upload plan"
        uses: actions/upload-artifact@v4
        with:
          name: tfplan
          path: tfplan

  terraform_apply:
    needs: [terraform_plan]
    name: "Terraform apply"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: "Setup Terraform"
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.9.8
          cli_config_credentials_token: ${{ secrets.TF_API_KEY }}

      - name: "Download plan"
        uses: actions/download-artifact@v4
        with:
          name: tfplan
          path: ./downloaded-tfplan

      #- name: "check"
      #  run : |
      #    ls -la

      - name: "Terraform init"
        run: |
          terraform init

      - name: "Terraform apply"
        run: |
          terraform apply ./downloaded-tfplan/tfplan